from __future__ import annotations

import re


INLINE_EMOJI_RE = re.compile(r"\[([A-Za-z\u4e00-\u9fff][A-Za-z0-9\u4e00-\u9fff_ !\-\u2011]{0,32})\]")


# WeChat's bracketed names are proprietary sticker shortcuts, not Apple emoji
# names. These Unicode characters are close visual fallbacks for text export.
INLINE_EMOJI_MAP = {
    "Smile": "😊",
    "Grimance": "😬",
    "Grimace": "😬",
    "Drool": "😍",
    "Scowl": "😐",
    "CoolGuy": "😎",
    "Cool": "😎",
    "Sob": "😭",
    "Shy": "☺️",
    "Silent": "🤐",
    "Slient": "🤐",
    "Sleep": "😴",
    "Cry": "😢",
    "Awkward": "😅",
    "Angry": "😠",
    "Tongue": "😛",
    "Grin": "😁",
    "Surprise": "😮",
    "Frown": "☹️",
    "Ruthless": "😤",
    "Blush": "😳",
    "Scream": "😱",
    "Puke": "🤮",
    "Chuckle": "😏",
    "Joyful": "😂",
    "Slight": "🙂",
    "Smug": "😏",
    "Hungry": "😋",
    "Drowsy": "😪",
    "Panic": "😰",
    "Sweat": "😓",
    "Laugh": "😄",
    "Commando": "😌",
    "Determined": "💪",
    "Scold": "😡",
    "Shocked": "😲",
    "Shhh": "🤫",
    "Dizzy": "😵",
    "Tormented": "😣",
    "Toasted": "😩",
    "Skull": "💀",
    "Hammer": "🔨",
    "Wave": "👋",
    "Speechless": "😶",
    "NosePick": "🙄",
    "Clap": "👏",
    "Shame": "😳",
    "Trick": "😈",
    "Bah! L": "😤",
    "Bah! R": "😤",
    "Yawn": "🥱",
    "Pooh-pooh": "😒",
    "PoohPooh": "😒",
    "Shrunken": "😞",
    "TearingUp": "🥹",
    "Sly": "😏",
    "Kiss": "😘",
    "Wrath": "😨",
    "Whimper": "🥺",
    "Cleaver": "🔪",
    "Watermelon": "🍉",
    "Beer": "🍺",
    "Basketball": "🏀",
    "PingPong": "🏓",
    "Coffee": "☕",
    "Rice": "🍚",
    "Pig": "🐷",
    "Rose": "🌹",
    "Wilt": "🥀",
    "Lips": "💋",
    "Heart": "❤️",
    "BrokenHeart": "💔",
    "Cake": "🎂",
    "Lightning": "⚡",
    "Bomb": "💣",
    "Dagger": "🗡️",
    "Soccer": "⚽",
    "Ladybug": "🐞",
    "Poop": "💩",
    "Moon": "🌙",
    "Sun": "☀️",
    "Gift": "🎁",
    "Hug": "🤗",
    "ThumbsUp": "👍",
    "ThumbsDown": "👎",
    "Shake": "🤝",
    "Peace": "✌️",
    "Fight": "🙏",
    "Beckon": "👋",
    "Fist": "✊",
    "Pinky": "🤙",
    "RockOn": "🤟",
    "Nuh-uh": "🙅",
    "NuhUh": "🙅",
    "OK": "👌",
    "InLove": "❤️",
    "Blowkiss": "😘",
    "Waddle": "🕺",
    "Tremble": "😖",
    "Aaagh!": "😫",
    "Aaagh": "😫",
    "Twirl": "🌀",
    "Kotow": "🙇",
    "Dramatic": "↩️",
    "JumpRope": "🤾",
    "Surrender": "🙌",
    "Hooray": "🙌",
    "Meditate": "🧘",
    "Smooch": "😘",
    "TaiChi L": "☯️",
    "TaiChi R": "☯️",
    "Doge": "🐶",
    "LetMeSee": "👀",
    "Emm": "🤔",
    "Hey": "👋",
    "Yeah": "👍",
    "Concerned": "😟",
    "Smirk": "😏",
    "Facepalm": "🤦",
    "微笑": "😊",
    "撇嘴": "😬",
    "色": "😍",
    "发呆": "😐",
    "得意": "😎",
    "流泪": "😭",
    "害羞": "☺️",
    "闭嘴": "🤐",
    "睡": "😴",
    "大哭": "😢",
    "尴尬": "😅",
    "发怒": "😠",
    "调皮": "😛",
    "呲牙": "😁",
    "惊讶": "😮",
    "难过": "☹️",
    "酷": "😎",
    "冷汗": "😓",
    "抓狂": "😱",
    "吐": "🤮",
    "偷笑": "😏",
    "愉快": "😂",
    "白眼": "🙄",
    "傲慢": "😏",
    "饥饿": "😋",
    "困": "😪",
    "惊恐": "😰",
    "流汗": "😓",
    "憨笑": "😄",
    "悠闲": "😌",
    "奋斗": "💪",
    "咒骂": "😡",
    "疑问": "😲",
    "嘘": "🤫",
    "晕": "😵",
    "疯了": "😣",
    "衰": "😩",
    "骷髅": "💀",
    "敲打": "🔨",
    "再见": "👋",
    "擦汗": "😓",
    "抠鼻": "🙄",
    "鼓掌": "👏",
    "糗大了": "😳",
    "坏笑": "😈",
    "左哼哼": "😤",
    "右哼哼": "😤",
    "哈欠": "🥱",
    "鄙视": "😒",
    "委屈": "🥺",
    "快哭了": "🥹",
    "阴险": "😏",
    "亲亲": "😘",
    "吓": "😨",
    "可怜": "🥺",
    "菜刀": "🔪",
    "西瓜": "🍉",
    "啤酒": "🍺",
    "篮球": "🏀",
    "乒乓": "🏓",
    "饭": "🍚",
    "猪头": "🐷",
    "玫瑰": "🌹",
    "凋谢": "🥀",
    "嘴唇": "💋",
    "爱心": "❤️",
    "心碎": "💔",
    "蛋糕": "🎂",
    "闪电": "⚡",
    "炸弹": "💣",
    "刀": "🗡️",
    "足球": "⚽",
    "瓢虫": "🐞",
    "便便": "💩",
    "月亮": "🌙",
    "太阳": "☀️",
    "礼物": "🎁",
    "拥抱": "🤗",
    "强": "👍",
    "弱": "👎",
    "握手": "🤝",
    "胜利": "✌️",
    "抱拳": "🙏",
    "勾引": "👋",
    "拳头": "✊",
    "差劲": "🤙",
    "爱你": "🤟",
    "NO": "🙅",
    "爱情": "❤️",
    "飞吻": "😘",
    "跳跳": "🕺",
    "发抖": "😖",
    "怄火": "😫",
    "转圈": "🌀",
    "磕头": "🙇",
    "回头": "↩️",
    "跳绳": "🤾",
    "投降": "🙌",
}


def replace_inline_emoji_codes(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        code = match.group(1).strip()
        normalized = code.replace("\u2011", "-").rstrip("!")
        return INLINE_EMOJI_MAP.get(code) or INLINE_EMOJI_MAP.get(normalized) or match.group(0)

    return INLINE_EMOJI_RE.sub(repl, text)
